security:
  basic:
    enabled: false
server:
  port: 8082
spring:
  jpa:    
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
postgres.url:
   5433
spring.datasource: 
  type: com.zaxxer.hikari.HikariDataSource
  url: jdbc:postgresql://localhost:${postgres.url}/resources
  username: postgres
  password: admin
  testWhileIdle: true
  validationQuery: SELECT 1
flyway:
  schemas:
    - public
  metaDataTableName: schema_version
http:
    multipart:
    max-file-size: 5MB
    max-request-size: 5MB
idp:
  url: localhost:8181
service:
  id: cm
  secret: cmpass