Insert into nodeType (type_id, type_name) values('1', 'image/jpeg');
Insert into node (node_id, type_id) values('s1', '1');
Insert into node (node_id,  type_id) values('s2', '1');
Insert into node (node_id, type_id) values('s3', '1');
Insert into node (node_id, type_id) values('1', '1');
Insert into node (node_id, type_id) values('nodepictureId1', '1');
Insert into node (node_id, type_id) values('nodepictureId2', '1');
Insert into node (node_id, type_id) values('nodepictureId3', '1');
Insert into node (node_id, type_id) values('nodepictureId4', '1');
Insert into node (node_id, type_id) values('nodepictureId5', '1');
Insert into node (node_id, type_id) values('nodepictureId6', '1');
Insert into node (node_id, type_id) values('nodepictureId7', '1');
Insert into node (node_id, type_id) values('nodepictureId8', '1');
Insert into node (node_id, type_id) values('nodepictureId9','1');
Insert into node (node_id, type_id) values('nodepictureId10','1');
Insert into node (node_id, type_id) values('nodepictureId11','1');
